base/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from front import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front.urls')),
    path('users/', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/urls.py
from django.urls import path
from . import views 



urlpatterns = [
    
    path('', views.home, name = 'home'),
    path('<str:tk>/', views.cv, name = 'cv'),
    path('update/skill', views.skills, name = 'skills'),
    path('update/language', views.language, name = 'languages'),
    path('update/about', views.about, name = 'about'),
    path('update/work', views.work, name = 'works'),
    path('update/education', views.education, name = 'education'),
    path('update/objective', views.objective, name = 'objective'),
    ]

front/models.py
from django.db import models
from users.models import CustomUser


CHOICES = (
    ('Beginner','Beginner'),
    ('Intermediate', 'Intermediate'),
    ('Advanced','Advanced'))



class Skill(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    sk = models.CharField(verbose_name="Skill", max_length=50)
    percent = models.CharField(verbose_name="How good are you?", max_length=30, choices=CHOICES, default='intermediate') 

    def __str__(self):
        return f'{self.sk} - {self.percent}'

class Language(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    lg = models.CharField(verbose_name="Language", max_length=50)
    percent = models.CharField(verbose_name="How good are you?", max_length=30, choices=CHOICES, default='intermediate')

    def __str__(self):
        return f'{self.sk} - {self.percent}'


class About(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    description = models.TextField(max_length=1500)

    def __str__(self):
        return f'{self.description}'


class Work(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    position = models.CharField(max_length=50)
    company = models.CharField(max_length=50)
    location = models.CharField(max_length=50) 
    work_description = models.TextField(max_length=500)
    start_date = models.DateField()
    end_date = models.DateField(verbose_name="End date(leave empty for current position)",null=True, blank=True)
    current = models.BooleanField(default=False)
    class Meta:
        ordering = ['-start_date']

    def __str__(self):
        return f'{self.position} - {self.company} - {self.location}'

class Education(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    institution_name = models.CharField(max_length=50)
    degree = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    graduation_year = models.DateField()
    description = models.TextField(max_length=1500)
    class Meta:
        ordering = ['-graduation_year']

    def __str__(self):
        return f'{self.institution_name} - {self.degree} - {self.location}'

class Objective(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    description = models.TextField(max_length=1500)

    def __str__(self):
        return f'{self.description}'

front/forms.py
from django import forms
from django.forms import ModelForm
from .models import Skill, Language, Work, Education, Objective, About



class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['sk','percent']

class LanguageForm(forms.ModelForm):
    class Meta:
        model = Language
        fields = ['lg','percent']

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = ['description']

class DateInput(forms.DateInput):
    input_type = 'date'

class WorkForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = ['company','position','location', 'work_description', 'start_date', 'end_date']
        widgets= { 'start_date': DateInput(), 'end_date': DateInput()}


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ['institution_name','degree', 'location', 'graduation_year', 'description']
        widgets= { 'graduation_year': DateInput()}


class ObjectiveForm(forms.ModelForm):
    class Meta:
        model = Objective
        fields = ['description']

front/views.py
from django.shortcuts import render
from users.models import CustomUser
from .forms import SkillForm, LanguageForm, WorkForm, EducationForm, ObjectiveForm,AboutForm
from .models import Skill, Language, Work, Education, Objective, About
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404


# Create your views here.


def home(request):
	return render(request, 'front/home.html')


def cv(request, tk):
	cv_owner = request.path
	cv_owner = cv_owner.replace('/','')
	data = get_object_or_404(CustomUser, tk=tk)
	# data = CustomUser.objects.all().get(tk = tk)
	return render(request, 'front/index.html',{'data':data ,'cv_owner':cv_owner })

@login_required
def skills(request):
	skill_form = SkillForm()
	if request.method == 'POST' or None:
		if "skill" in request.POST:
			skill_form  = SkillForm(request.POST)
			if skill_form.is_valid():
				Skill(author = request.user, sk = request.POST.get("sk"),percent = request.POST.get("percent")).save()
				skill_form = SkillForm()
		if "delete" in request.POST:
			skill_id = request.POST.get("skill.id")
			Skill.objects.get(id=skill_id).delete()

	return render(request, 'front/skills.html',{'skill_form': skill_form})

@login_required
def language(request):
	language_form = LanguageForm()
	if request.method == 'POST' or None:
		if "language" in request.POST:
			language_form  = LanguageForm(request.POST)
			if language_form.is_valid():
				Language(author = request.user, lg = request.POST.get("lg"),percent = request.POST.get("percent")).save()
				language_form = LanguageForm()
		if "delete" in request.POST:
			language_id = request.POST.get("language.id")
			Language.objects.get(id=language_id).delete()

	return render(request, 'front/languages.html',{'language_form': language_form})





@login_required
def work(request):
	work_form = WorkForm()
	if request.method == 'POST' or None:
		if "work" in request.POST:
			work_form  = WorkForm(request.POST)
			if work_form.is_valid():
				work_form.cleaned_data['author']=request.user
				Work.objects.create(**work_form.cleaned_data)
				work_form = WorkForm()
		if "delete" in request.POST:
			work_id = request.POST.get("work.id")
			Work.objects.get(id = work_id).delete()

	return render(request, 'front/works.html',{'work_form': work_form})






# @login_required
# def work(request):
# 	work_form = WorkForm()
# 	if request.method == 'POST' or None:
# 		if "work" in request.POST:
# 			work_form  = WorkForm(request.POST)
# 			if work_form.is_valid():
# 				Work(author = request.user, 
# 					work_description = request.POST.get("work_description"),
# 					position = request.POST.get("position"),
# 					company = request.POST.get("company"),
# 					location = request.POST.get("location"),
# 					start_date = request.POST.get("start_date"),
# 					end_date = request.POST.get("end_date")).save()
# 				work_form = WorkForm()
# 		if "delete" in request.POST:
# 			work_id = request.POST.get("work.id")
# 			Work.objects.get(id = work_id).delete()

# 	return render(request, 'front/works.html',{'work_form': work_form})

@login_required
def education(request):
	education_form = EducationForm()
	if request.method == 'POST' or None:
		if "education" in request.POST:
			education_form  = EducationForm(request.POST)
			if education_form.is_valid():
				Education(author = request.user, 
					institution_name = request.POST.get("institution_name"),
					degree = request.POST.get("degree"),
					location = request.POST.get("location"),
					graduation_year = request.POST.get("graduation_year"),
					description = request.POST.get("description")).save()
				education_form = WorkForm()
		if "delete" in request.POST:
			education_id = request.POST.get("education.id")
			Education.objects.get(id = education_id).delete()

	return render(request, 'front/education.html',{'education_form': education_form})


@login_required
def objective(request):
	objective_form = ObjectiveForm()
	if request.method == 'POST' or None:
		if "objective" in request.POST:
			objective_form  = ObjectiveForm(request.POST)
			if objective_form.is_valid():
				Objective(author = request.user, description = request.POST.get("description")).save()
				objective_form = ObjectiveForm()
		if "delete" in request.POST:
			objective_id = request.POST.get("objective.id")
			Objective.objects.get(id = objective_id).delete()

	return render(request, 'front/objective.html',{'objective_form': objective_form})

@login_required
def about(request):
	about_form = AboutForm()
	if request.method == 'POST' or None:
		if "about" in request.POST:
			about_form  = AboutForm(request.POST)
			if about_form.is_valid():
				About(author = request.user, description = request.POST.get("description")).save()
				about_form = AboutForm()
		if "delete" in request.POST:
			about_id = request.POST.get("about.id")
			About.objects.get(id = about_id).delete()

	return render(request, 'front/about.html',{'about_form': about_form})

front/templates/front/about.html
{% extends 'front/base.html' %}
{% load crispy_forms_tags %}  
{% block content %}

<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<h2>About</h2>
</div>
{% for ob in user.about_set.all %}
	<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<div  class="content-section">
		<div class="d-flex justify-content-between">
			<h4 style="word-break: break-word">{{ob|linebreaksbr}}</h4>
			<form method="POST">{% csrf_token %}
			<button class="btn btn-danger btn-sm mt-2 mb-1" type="submit" name = "delete" >Delete</button>
            <input type="hidden" name="about.id" value="{{ob.id}}">
			</form>
		</div>
	</div>
	</div>
{% empty %}
	<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<div  class="content-section">
		<h4>No about added yet</h4>
	</div>
	</div>
{% endfor %}

<div class="w3-content w3-margin-top" style="max-width:800px;">
	<div  class="content-section">
	        <form method="POST">
	        	<div style="text-align:center;">
	        	<h3>Add about</h3>
	        	</div>
	     
	            {% csrf_token %} {{ about_form|crispy }}

	            <div class="form-group" style="">
	            	<button style="background-color: #009688!important; border-width: 0px;" type="Submit" class="btn btn-primary" name="about">Add</button>
	            </div>	 	            
				</div>	
	            </div>
	        </form>
	    </div>

<div class="w3-content w3-margin-top" style="max-width:800px;">
	<div  class="content-section">
		<div class="d-flex justify-content-between">
			<a href="{% url 'languages' %}" class="button">&#8592; Back</a>
			<a href="{% url 'works' %}" class="button">Next &#8594;</a>
		</div>
</div>
</div>
</div>
{% endblock %}

front/templates/front/education.html
{% extends 'front/base.html' %}
{% load crispy_forms_tags %}  
{% block content %}

<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<h2>Education</h2>
</div>
{% for education in user.education_set.all %}
	<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<div  class="content-section">
		<div class="d-flex justify-content-between">
			<h4>{{education.institution_name}} / {{education.degree}} / {{education.graduation_year}}</h4>
			<form method="POST">{% csrf_token %}
			<button class="btn btn-danger btn-sm mt-2 mb-1" type="submit" name = "delete" >Delete</button>
            <input type="hidden" name="education.id" value="{{education.id}}">
			</form>
		</div>
	</div>
	</div>
{% empty %}
	<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<div  class="content-section">
		<h4>No education added yet</h4>
	</div>
	</div>
{% endfor %}

<div class="w3-content w3-margin-top" style="max-width:800px;">
	<div  class="content-section">
	        <form method="POST">
	        	<div style="text-align:center;">
	        	<h3>Add Education</h3>
	        	</div>
	     
	            {% csrf_token %} {{ education_form|crispy }}

	            <div class="form-group" style="">
	            	<button style="background-color: #009688!important; border-width: 0px;" type="Submit" class="btn btn-primary" name="education">Add</button>
	            </div>	 	            
				</div>	
	            </div>
	        </form>
	    </div>

<div class="w3-content w3-margin-top" style="max-width:800px;">
	<div  class="content-section">
		<div class="d-flex justify-content-between">
			<a href="{% url 'about' %}" class="button">&#8592; Back</a>
			<a href="{% url 'objective' %}" class="button">Next &#8594;</a>
		</div>
</div>
</div>
</div>
{% endblock %}

front/templates/front/index.html
{% extends 'front/base.html' %}
{% block content%}
<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1300px;min-width:150px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <img src="{{data.image.url}}" style="width:100%;" alt="Avatar">

          <div class="w3-display-bottomleft w3-container w3-text-black">
            {% if user.is_authenticated  and user.tk == cv_owner %}
            <div style="display: flex; justify-content: space-between;">
              <a style="color:#009688!important;margin-bottom: 9px;" href="{% url 'profile' %}">Update Profile</a>
             
                       </div>
            {% endif %}
          </div>
        </div>
        <div class="w3-container">
          <br>
           <h2 style="color: #757575!important"><strong>{{data.username}}</strong></h2>
          <br>
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>{{data.professional_training}}</p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i>{{data.city}}, {{data.country}}</p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>{{data.email}}</p>
          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i>{{data.phone}}</p>
          <hr>
          <!-- Skills section -->
          {% if user.is_authenticated  and user.tk == cv_owner %}

          <div style="display: flex; justify-content: space-between;">
            <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>
            <a href="{% url 'skills' %}"><p style="color:#009688!important">Update</p></a>
          </div>
             {% for sk in data.skill_set.all %}
            <p>{{sk.sk}}</p>
                    {% if sk.percent == "Beginner" %}
                        {% with perc=30 %}   
            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{sk.percent}}</div>
            </div><br>
                       {% endwith %}
                    {% elif sk.percent == "Intermediate"%}
                      {% with perc=60 %} 
                            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{sk.percent}}</div>
            </div><br>
                        {% endwith %}
                    {% elif sk.percent == "Advanced"%}
                      {% with perc=100 %} 
                            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{sk.percent}}</div>
            </div><br>
                        {% endwith %}
                      {% endif %}
              {%endfor%}
            {% else %}
            <div style="display: flex; justify-content: space-between;">
            <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>

          </div>
             {% for sk in data.skill_set.all %}
            <p>{{sk.sk}}</p>
                    {% if sk.percent == "Beginner" %}
                        {% with perc=30 %}   
            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{sk.percent}}</div>
            </div><br>
                       {% endwith %}
                    {% elif sk.percent == "Intermediate"%}
                      {% with perc=60 %} 
                            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{sk.percent}}</div>
            </div><br>
                        {% endwith %}
                    {% elif sk.percent == "Advanced"%}
                      {% with perc=100 %} 
                            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{sk.percent}}</div>
            </div><br>
                        {% endwith %}
                      {% endif %}
              {%endfor%}
               
            {% endif %}
            <hr>


            <!-- End Skills section -->
            <!-- Language section -->


           
         {% if user.is_authenticated  and user.tk == cv_owner %}

          <div style="display: flex; justify-content: space-between;">
            <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
            <a href="{% url 'languages' %}"><p style="color:#009688!important">Update</p></a>
          </div>
             {% for lg in data.language_set.all %}
            <p>{{lg.lg}}</p>
                    {% if lg.percent == "Beginner" %}
                        {% with perc=30 %}   
            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{lg.percent}}</div>
            </div><br>
                       {% endwith %}
                    {% elif lg.percent == "Intermediate"%}
                      {% with perc=60 %} 
                            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{lg.percent}}</div>
            </div><br>
                        {% endwith %}
                    {% elif lg.percent == "Advanced"%}
                      {% with perc=100 %} 
                            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{lg.percent}}</div>
            </div><br>
                        {% endwith %}
                      {% endif %}
              {%endfor%}
            {% else %}
            <div style="display: flex; justify-content: space-between;">
            <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>
          </div>
             {% for lg in data.language_set.all %}
            <p>{{lg.lg}}</p>
                    {% if lg.percent == "Beginner" %}
                        {% with perc=30 %}   
            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{lg.percent}}</div>
            </div><br>
                       {% endwith %}
                    {% elif lg.percent == "Intermediate"%}
                      {% with perc=60 %} 
                            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{lg.percent}}</div>
            </div><br>
                        {% endwith %}
                    {% elif lg.percent == "Advanced"%}
                      {% with perc=100 %} 
                            <div class="w3-light-grey w3-round-xlarge w3-small">
              <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:{{perc}}%">{{lg.percent}}</div>
            </div><br>
                        {% endwith %}
                      {% endif %}
              {%endfor%}

            {% endif %}
            <!-- End Language section -->
          <br>
        </div>
      </div>
      <br>
  
 
    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    
    <div class="w3-twothird">

           <!-- about -->
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <div style="display: flex; justify-content: space-between;">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-user fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i><strong>About</strong></h2>
          {% if user.is_authenticated  and user.tk == cv_owner %}
          <a href="{% url 'about' %}"><p style="padding-top: 35px; padding-right: 15px; color:#009688!important">Update</p></a>
          {% endif %}
        </div>        
        <div class="w3-container" style="min-width:30px;">
          {% for ob in data.about_set.all%}
          <p style="word-break: break-word">{{ ob.description | linebreaksbr}}</p>
          <br>
          {%endfor%}
        </div>
      </div>

        <!-- work -->

      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <div style="display: flex; justify-content: space-between;">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i><strong>Work Experience</strong></h2>
          {% if user.is_authenticated  and user.tk == cv_owner %}
          <a href="{% url 'works'%}"><p style="padding-top: 35px;padding-right: 15px;color:#009688!important">Update</p></a>
          {% endif %}
        </div>
        <div class="w3-container">
          {% for dt in data.work_set.all%}
          <h5 class="w3-opacity" style="word-break: break-word"><b>{{ dt.company }} / {{ dt.position }}</b></h5>
          <h6 class="w3-text-teal"><i class="fa fa-globe fa-fw w3-margin-right"></i>{{ dt.location }}</h6>
          {% if dt.end_date %}
          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>{{dt.start_date}} - {{dt.end_date}}</h6> 
          {% else %}
          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>{{dt.start_date}} - <span style="padding-bottom:3px ;" class="w3-tag w3-teal w3-round">Current position</span></h6> 
          
            {% endif %}

          <p style="word-break: break-word">{{ dt.work_description | linebreaksbr}}</p>
          <br>
          {%endfor%}
        </div>
      </div>

       <!-- Education -->
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <div style="display: flex; justify-content: space-between;">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i><strong>Education</strong></h2>
          {% if user.is_authenticated  and user.tk == cv_owner %}
          <a href="{% url 'education'%}"><p style="padding-top: 35px;padding-right: 15px;color:#009688!important">Update</p></a>
          {% endif %}
        </div>
        <div class="w3-container">
          {% for ed in data.education_set.all%}
          <h5 class="w3-opacity"><b>{{ ed.institution_name }} / {{ ed.degree}}</b></h5>
          <h6 class="w3-text-teal"><i class="fa fa-globe fa-fw w3-margin-right"></i>{{ ed.location }}</h6>
          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>{{ed.graduation_year}}</h6>
          <p>{{ ed.description }}</p>
          <br>
          {%endfor%}
        </div>
      </div>
                <!-- Objective -->
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <div style="display: flex; justify-content: space-between;">
          <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-question-circle fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i><strong>Objective</strong></h2>
          {% if user.is_authenticated  and user.tk == cv_owner %}
          <a href="{% url 'objective' %}"><p style="padding-top: 35px;padding-right: 15px;color:#009688!important">Update</p></a>
          {% endif %}
        </div>        
        <div class="w3-container"><br>
          {% for ob in data.objective_set.all%}
          <p style="color:#757575; margin-top: -30px;word-break: break-word">{{ ob.description | linebreaksbr}}</p>
          <br>
          {%endfor%}
        </div>
      </div>

    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
  <!-- End Page Container -->
</div>

{% endblock %}

front/templates/front/languages.html
{% extends 'front/base.html' %}
{% load crispy_forms_tags %}  
{% block content %}

<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<h2>Language</h2>
</div>
{% for language in user.language_set.all %}
	<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<div  class="content-section">
		<div class="d-flex justify-content-between">
			<h4>{{language.lg}} / {{language.percent}}</h4>
			<form method="POST">{% csrf_token %}
			<button class="btn btn-danger btn-sm mt-2 mb-1" type="submit" name = "delete" >Delete</button>
            <input type="hidden" name="language.id" value="{{language.id}}">
			</form>
		</div>
	</div>
	</div>
{% empty %}
	<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<div  class="content-section">
		<h4>No language added yet</h4>
	</div>
	</div>
{% endfor %}

<div class="w3-content w3-margin-top" style="max-width:800px;">
	<div  class="content-section">
	        <form method="POST">
	        	<div style="text-align:center;">
	        	<h3>Add Language</h3>
	        	</div>
	     
	            {% csrf_token %} {{ language_form|crispy }}

	            <div class="form-group" style="">
	            	<button style="background-color: #009688!important; border-width: 0px;" type="Submit" class="btn btn-primary" name="language">Add</button>
	            </div>	 	            
				</div>	
	            </div>
	        </form>
	    </div>

<div class="w3-content w3-margin-top" style="max-width:800px;">
	<div  class="content-section">
		<div class="d-flex justify-content-between">
			<a href="{% url 'skills' %}" class="button">&#8592; Back</a>
			<a href="{% url 'about' %}" class="button">Next &#8594;</a>
		</div>
</div>
</div>
</div>
{% endblock %}

front/templates/front/objective.html
{% extends 'front/base.html' %}
{% load crispy_forms_tags %}  
{% block content %}

<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<h2>Objective</h2>
</div>
{% for ob in user.objective_set.all %}
	<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<div  class="content-section">
		<div class="d-flex justify-content-between">
			<h4 style="word-break: break-word">{{ob|linebreaksbr}}</h4>
			<form method="POST">{% csrf_token %}
			<button class="btn btn-danger btn-sm mt-2 mb-1" type="submit" name = "delete" >Delete</button>
            <input type="hidden" name="objective.id" value="{{ob.id}}">
			</form>
		</div>
	</div>
	</div>
{% empty %}
	<div class="w3-content w3-margin-top" style="max-width:800px;text-align:center ;">
	<div  class="content-section">
		<h4>No objective added yet</h4>
	</div>
	</div>
{% endfor %}

<div class="w3-content w3-margin-top" style="max-width:800px;">
	<div  class="content-section">
	        <form method="POST">
	        	<div style="text-align:center;">
	        	<h3>Add objective</h3>
	        	</div>
	     
	            {% csrf_token %} {{ objective_form|crispy }}

	            <div class="form-group" style="">
	            	<button style="background-color: #009688!important; border-width: 0px;" type="Submit" class="btn btn-primary" name="objective">Add</button>
	            </div>	 	            
				</div>	
	            </div>
	        </form>
	    </div>

<div class="w3-content w3-margin-top" style="max-width:800px;">
	<div  class="content-section">
		<div class="d-flex justify-content-between">
			<a href="{% url 'education' %}" class="button">&#8592; Back</a>
			<a href="{% url 'cv' user.tk %}" class="button">Finish</a>
		</div>
</div>
</div>
</div>
{% endblock %}